name: C++ Build Check

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install C++ compiler
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build project
      run: |
        g++ -std=c++11 \
        main.cpp \
        models/Product.cpp \
        models/Customer.cpp \
        models/Staff.cpp \
        core/FileHandler.cpp \
        -o cafe_management
